import { Router } from 'express';

import abuseRoutes from './abuse';
import agentLogsRoutes from './agentLogs';
import aiRoutes from './ai';
import auditRoutes from './audit';
import authRoutes from './auth';
import contactsNeonRoutes from './contactsNeon';
import crisisRoutes from './crisis';
import dispatchRoutes from './dispatch';
import emergencyRoutes from './emergency';
import fcmRoutes from './fcm';
import healthRoutes from './health';
import userRoutes from './user';
import validatorRoutes from './validator';
import voiceThreatRoutes from './voiceThreat';
import whatsappRoutes from './whatsapp';
import workflowRoutes from './workflow';
import emergencyContactsRoutes from './emergencyContacts';
import emergencyContactsSimpleRoutes from './emergencyContactsSimple';
import tracesRoutes from './traces';
import locationRoutes from './location';
import emergencySMSRoutes from './emergencySMS';
import neonDBRoutes from './neonDB';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/emergency', emergencyRoutes);
router.use('/contacts/emergency', emergencyContactsRoutes);
router.use('/emergency-contacts', emergencyContactsSimpleRoutes);
router.use('/traces', tracesRoutes);
router.use('/user', userRoutes);
router.use('/ai', aiRoutes);
router.use('/dispatch', dispatchRoutes);
router.use('/validator', validatorRoutes);
router.use('/workflow', workflowRoutes);
router.use('/crisis', crisisRoutes);
router.use('/fcm', fcmRoutes);
router.use('/location', locationRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/audit', auditRoutes);
router.use('/abuse', abuseRoutes);
router.use('/voice-threat', voiceThreatRoutes);
router.use('/emergency-sms', emergencySMSRoutes);
router.use('/agent-logs', agentLogsRoutes);
router.use('/neon', neonDBRoutes);
router.use('/contacts-neon', contactsNeonRoutes);

export default router;
